[isolated]
# Rules for containers (namespaces, cgroups, etc)

[host]
# Rules for core services (compositor, init-bridge)
guarddog = {
    name = "/bin/guarddog",
    args = "",

    needs_dev = ["/dev/console", "/dev/tty0"],
    on_exit = "restart"
}
